<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.2.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerPlatformGovernance.Application\PowerPlatformGovernance.Application.csproj" />
    <ProjectReference Include="..\PowerPlatformGovernance.Domain\PowerPlatformGovernance.Domain.csproj" />
  </ItemGroup>
</Project>
